### PR TITLE
transit assignment updates for v9 network

### PR DESCRIPTION
**Pull request by yueshuaing**
## What is the testing plan?

*Demonstrate the code is solid by discussing how results are verified and covered by tests*

 - [ ] Code for this PR is covered in tests 
 - [ ] Code passes all existing tests

## Code formatting
*Code should be PEP8 compliant before merging by running a package like [`black`](https://pypi.org/project/black/)*

 - [ ] Code linted

## Applicable Issues
*Please do not create a Pull Request without creating an issue first.*

*Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes.*

 
#### Issues List

 -  closes...
 -  closes...

### CODE REVIEW

**Comment by xyzjayne** [comment]
Thank you for the update. As I'm not familiar with the transit assignment logic, could you point out where specifically my review can be helpful?

**Comment by yueshuaing** [comment]
>

**Comment by yueshuaing** [comment]
> Thank you for the update. As I'm not familiar with the transit assignment logic, could you point out where specifically my review can be helpful?

Hi Jayne, I'm still drafting the transit assignment changes, but they should be ready later today. Could you please review the highway assignment changes you merged from develop_bart (for example the toml files)? I got several merge conflicts when I checked in my changes. Thanks!

**Comment by xyzjayne** [comment]
The following config items need to be updated/reviewed in ``develop_bart_transit_dev_v9``:

- RunConfig
  - warmstart_check
- HouseholdConfig and [household]
  - ctramp_hh_file
  - copy_from_examples
  - [household.income_segment]
- ConvergenceReportConfig and [highway.convergence]
  - output_convergence_report_path = "output_summaries/highway_convergence_report.txt"
  - output_triptable_path = "output_summaries/trip_tables_{iteration}.omx"
  - output_skim_path = "output_summaries/skims_{iteration}.omx"
  - selected_od_pair = [1,100]
  - selected_links = [5,10,15]
  - skim_selected_time_periods = ["am","pm"]
  - output_network_attr_filename = "output_summaries/network_attrs_{iteration}.parquet"
  - output_network_summary_filename = "output_summaries/network_summary_{iteration}.csv"
- TransitModeConfig
  - initial_boarding_penalty (it's no longer in the toml file, please verify)
  - transfer_boarding_penalty (it's no longer in the toml file, please verify)

**Pull request merged**
